### PR TITLE
Updated DSC website

### PR DESCRIPTION
**Pull request by yk1ax**
All images and links added
and all the icons for the links are also properly ordered

### CODE REVIEW

**Comment by yk1ax** [comment]
@GOVINDDIXIT you can review it

**Comment by GOVINDDIXIT** [comment]
@yk1ax remove extra space b/w profile pics and social links

**Comment by yk1ax** [comment]
@GOVINDDIXIT I'm on it

**Comment by yk1ax** [comment]
@GOVINDDIXIT removed extra space b/w profile pics and social links, you can review it now

**Review by GOVINDDIXIT — APPROVED** [review]
Good Work 👍

**Pull request merged**
