### PR TITLE
Teams-Updated

### PR DESCRIPTION
**Pull request by MightyMoin**
Updated teams and added time line.
ezgif com-video-to-gif

### CODE REVIEW

**Comment by damn-dvlpr** [comment]
Archive button needs work.

**Comment by damn-dvlpr** [comment]
Fix the mobile view of archive button.

**Comment by refactor-droidyy** [comment]
@MightyMoin add Ram Bharos to the technical lead section and change the core leads text to core members 
Nice work  @damn-dvlpr @MightyMoin 🤘🤘

**Comment by damn-dvlpr** [comment]
Merged Pull of Ritish.

**Pull request closed without merging**
